<?= $this->doctype() ?>

<?php  
$user = '';
if (isset($this->authService)) {
    if ($this->authService->hasIdentity()) {
        $user = $this->authService->getIdentity();
   }
} 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF3 Online Market')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Online Market
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <!-- //*** use the "navigation()" view helper instead of hard-coding menu items -->
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('market') ?>">Home</a></li>
                        <li class="active"><a href="<?= $this->url('market/post') ?>">Post</a></li>
                        <li class="active"><a href="<?= $this->url('events') ?>">Events</a></li>
                        <li class="active"><a href="<?= $this->url('doctrine') ?>">Doctrine</a></li>
                        <?php if ($user) : ?>
                        <li class="active"><a href="<?= $this->url('messages') ?>">Messages</a></li>
                        <li class="active"><a href="<?= $this->url('login', ['action' => 'logout']) ?>">Logout</a></li>
                        <?php else : ?>
                        <li class="active"><a href="<?= $this->url('login', ['action' => 'login']) ?>">Login</a></li>
                        <?php endif; ?>
                    </ul>
                    <div style="float:right;vertical-align:bottom;">
                        <br>
                        <span style="color:white;">Logged In As: <?= ($user) ? $user->getEmail() : 'Guest' ?></span>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container">

            <div class="row">

                <div class="col-md-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Categories</h3>
                        </div>
                        <div class="panel-body">
                            <?= $this->leftLinks($this->categories, '/market/view/category'); ?>
                        </div>
                    </div>
                </div>

                <div class="col-md-10">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?= $this->content ?>
                        </div>
                        <hr>
                        <footer>
                            <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
                        </footer>
                    </div>
                </div>

            </div>

        </div>

        <?= $this->inlineScript() ?>

    </body>
</html>
